import PartType from '@entities/part-type-enum';
import Stats from '@entities/stats';
import getImageUrl from '@utils/getImageUrl';

const data: Stats[] = [
    {
        name: 'Super Glider',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Cloud Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Wario Wing',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    } as Stats,
    {
        name: 'Waddle Wing',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Peach Parasol',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Parachute',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Parafoil',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Flower Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Bowser Kite',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Plane Glider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    } as Stats,
    {
        name: 'MKTV Parafoil',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Gold Glider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    } as Stats,
    {
        name: 'Hylian Kite',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Paraglider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    } as Stats,
    {
        name: 'Paper Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    } as Stats
];

data.forEach(item => item.imageUrl = getImageUrl(item, PartType.Glider));

export default data;