import Stats from '../../entities/stats';
import getImageUrl from '@utils/getImageUrl';
import PartType from '@entities/part-type-enum';

const data: Stats[] = [
	{
		name: 'Standard Kart',
		speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0,
	} as Stats,
	{
		name: 'Pipe Frame',
		speedGnd: -0.5,
		speedWtr: 0,
		speedAir: -0.5,
		speedGty: -0.5,
		acceleration: 0.5,
		weight: -0.25,
		handlingGnd: 0.5,
		handlingWtr: 0.5,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0.5
	} as Stats,
	{
		name: 'Mach 8',
		speedGnd: 0,
		speedWtr: 0,
		speedAir: 0.25,
		speedGty: 0.5,
		acceleration: -0.25,
		weight: 0.25,
		handlingGnd: -0.25,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0
	} as Stats,
	{
		name: 'Steel Driver',
		speedGnd: 0.25,
		speedWtr: 0.5,
		speedAir: -0.75,
		speedGty: -0.25,
		acceleration: -0.75,
		weight: 0.5,
		handlingGnd: -0.5,
		handlingWtr: 0.75,
		handlingAir: -0.5,
		handlingGty: -0.5,
		grip: 0,
		miniturbo: -0.5
	} as Stats,
	{
		name: 'Cat Cruiser',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0.25,
		speedGty: 0,
		acceleration: 0.25,
		weight: 0,
		handlingGnd: 0.25,
		handlingWtr: 0,
		handlingAir: 0.25,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0.25
	} as Stats,
	{
		name: 'Circuit Special',
		speedGnd: 0.5,
		speedWtr: -0.5,
		speedAir: -0.25,
		speedGty: 0.25,
		acceleration: -0.75,
		weight: 0.25,
		handlingGnd: -0.5,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.25,
		grip: -0.5,
		miniturbo: -0.75
	} as Stats,
	{
		name: 'Tri-Speeder',
		speedGnd: 0.25,
		speedWtr: 0.5,
		speedAir: -0.75,
		speedGty: -0.25,
		acceleration: -0.75,
		weight: 0.5,
		handlingGnd: -0.5,
		handlingWtr: 0.75,
		handlingAir: -0.5,
		handlingGty: -0.5,
		grip: 0,
		miniturbo: -0.5
	} as Stats,
	{
		name: 'Badwagon',
		speedGnd: 0.5,
		speedWtr: -0.25,
		speedAir: -0.5,
		speedGty: 0,
		acceleration: -1,
		weight: 0.5,
		handlingGnd: -0.75,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.5,
		grip: 0.5,
		miniturbo: -1
	} as Stats,
	{
		name: 'Prancer',
		speedGnd: 0.25,
		speedWtr: 0,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: -0.25,
		handlingGnd: 0,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: -0.25,
		grip: -0.25,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'Biddybuggy',
		speedGnd: -0.75,
		speedWtr: -0.5,
		speedAir: -0.5,
		speedGty: -0.25,
		acceleration: 0.75,
		weight: -0.5,
		handlingGnd: 0.5,
		handlingWtr: 0.5,
		handlingAir: 0.25,
		handlingGty: 0.5,
		grip: 0.25,
		miniturbo: 0.75
	} as Stats,
	{
		name: 'Landship',
		speedGnd: -0.5,
		speedWtr: 0.5,
		speedAir: -0.25,
		speedGty: -0.75,
		acceleration: 0.5,
		weight: -0.5,
		handlingGnd: 0.25,
		handlingWtr: 0.75,
		handlingAir: 0,
		handlingGty: -0.25,
		grip: 0.75,
		miniturbo: 0.5
	} as Stats,
	{
		name: 'Sneeker',
		speedGnd: 0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0,
		handlingGnd: 0,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0,
		grip: -0.75,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'Sports Coupe',
		speedGnd: 0,
		speedWtr: 0,
		speedAir: 0.25,
		speedGty: 0.5,
		acceleration: -0.25,
		weight: 0.25,
		handlingGnd: -0.25,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0
	} as Stats,
	{
		name: 'Gold Standard',
		speedGnd: 0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0,
		handlingGnd: 0,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0,
		grip: -0.75,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'GLA',
		speedGnd: 0.5,
		speedWtr: -0.25,
		speedAir: -0.5,
		speedGty: 0,
		acceleration: -1,
		weight: 0.5,
		handlingGnd: -0.75,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.5,
		grip: 0.5,
		miniturbo: -1
	} as Stats,
	{
		name: 'W 25 Silver Arrow',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: 0.25,
		weight: -0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: 0.25,
		grip: 0.5,
		miniturbo: 0.25
	} as Stats,
	{
		name: '300 SL Roadster',
		speedGnd: 0,
		speedWtr: 0,
		speedAir: 0,
		speedGty: 0,
		acceleration: 0,
		weight: 0,
		handlingGnd: 0,
		handlingWtr: 0,
		handlingAir: 0,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0
	} as Stats,
	{
		name: 'Blue Falcon',
		speedGnd: 0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: -0.25,
		weight: -0.5,
		handlingGnd: -0.25,
		handlingWtr: 0.25,
		handlingAir: -0.5,
		handlingGty: 0.5,
		grip: 0,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'Tanooki Kart',
		speedGnd: -0.25,
		speedWtr: 0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.5,
		handlingAir: 0,
		handlingGty: 0,
		grip: 1,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'B Dasher',
		speedGnd: 0.5,
		speedWtr: -0.5,
		speedAir: -0.25,
		speedGty: 0.25,
		acceleration: -0.75,
		weight: 0.25,
		handlingGnd: -0.5,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.25,
		grip: -0.5,
		miniturbo: -0.75
	} as Stats,
	{
		name: 'Streetle',
		speedGnd: -0.5,
		speedWtr: 0.5,
		speedAir: -0.25,
		speedGty: -0.75,
		acceleration: 0.5,
		weight: -0.5,
		handlingGnd: 0.25,
		handlingWtr: 0.75,
		handlingAir: 0,
		handlingGty: -0.25,
		grip: 0.75,
		miniturbo: 0.5
	} as Stats,
	{
		name: 'P-Wing',
		speedGnd: 0.5,
		speedWtr: -0.5,
		speedAir: -0.25,
		speedGty: 0.25,
		acceleration: -0.75,
		weight: 0.25,
		handlingGnd: -0.5,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.25,
		grip: -0.5,
		miniturbo: -0.75
	} as Stats,
	{
		name: 'Koopa Clown',
		speedGnd: -0.25,
		speedWtr: 0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.5,
		handlingAir: 0,
		handlingGty: 0,
		grip: 1,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'Standard Bike',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: 0.25,
		weight: -0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: 0.25,
		grip: 0.5,
		miniturbo: 0.25
	} as Stats,
	{
		name: 'Comet',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0.25,
		speedGty: 0,
		acceleration: 0.25,
		weight: 0,
		handlingGnd: 0.25,
		handlingWtr: 0,
		handlingAir: 0.25,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0.25,
		insideDrift: true
	} as Stats,
	{
		name: 'Sport Bike',
		speedGnd: 0.25,
		speedWtr: 0,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: -0.25,
		handlingGnd: 0,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: -0.25,
		grip: -0.25,
		miniturbo: -0.25,
		insideDrift: true
	} as Stats,
	{
		name: 'The Duke',
		speedGnd: 0,
		speedWtr: 0,
		speedAir: 0,
		speedGty: 0,
		acceleration: 0,
		weight: 0,
		handlingGnd: 0,
		handlingWtr: 0,
		handlingAir: 0,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0
	} as Stats,
	{
		name: 'Flame Rider',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: 0.25,
		weight: -0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: 0.25,
		grip: 0.5,
		miniturbo: 0.25
	} as Stats,
	{
		name: 'Varmint',
		speedGnd: -0.5,
		speedWtr: 0,
		speedAir: -0.5,
		speedGty: -0.5,
		acceleration: 0.5,
		weight: -0.25,
		handlingGnd: 0.5,
		handlingWtr: 0.5,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0.5
	} as Stats,
	{
		name: 'Mr Scooty',
		speedGnd: -0.75,
		speedWtr: -0.5,
		speedAir: -0.5,
		speedGty: -0.25,
		acceleration: 0.75,
		weight: -0.5,
		handlingGnd: 0.5,
		handlingWtr: 0.5,
		handlingAir: 0.25,
		handlingGty: 0.5,
		grip: 0.25,
		miniturbo: 0.75
	} as Stats,
	{
		name: 'Jet Bike',
		speedGnd: 0.25,
		speedWtr: 0,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: -0.25,
		handlingGnd: 0,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: -0.25,
		grip: -0.25,
		miniturbo: -0.25,
		insideDrift: true
	} as Stats,
	{
		name: 'Yoshi Bike',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0.25,
		speedGty: 0,
		acceleration: 0.25,
		weight: 0,
		handlingGnd: 0.25,
		handlingWtr: 0,
		handlingAir: 0.25,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0.25,
		insideDrift: true
	} as Stats,
	{
		name: 'Master Cycle',
		speedGnd: 0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0,
		handlingGnd: 0,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0,
		grip: -0.75,
		miniturbo: -0.25,
		insideDrift: true
	} as Stats,
	{
		name: 'Master Cycle Zero',
		speedGnd: -0.25,
		speedWtr: 0.25,
		speedAir: 0,
		speedGty: 0,
		acceleration: -0.5,
		weight: 0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.5,
		handlingAir: 0,
		handlingGty: 0,
		grip: 1,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'City Tripper',
		speedGnd: -0.5,
		speedWtr: 0,
		speedAir: -0.5,
		speedGty: -0.5,
		acceleration: 0.5,
		weight: -0.25,
		handlingGnd: 0.5,
		handlingWtr: 0.5,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0.5
	} as Stats,
	{
		name: 'Standard ATV',
		speedGnd: 0.5,
		speedWtr: -0.25,
		speedAir: -0.5,
		speedGty: 0,
		acceleration: -1,
		weight: 0.5,
		handlingGnd: -0.75,
		handlingWtr: -0.25,
		handlingAir: -0.75,
		handlingGty: -0.5,
		grip: 0.5,
		miniturbo: -1
	} as Stats,
	{
		name: 'Wild Wiggler',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: 0.25,
		weight: -0.25,
		handlingGnd: 0.25,
		handlingWtr: 0.25,
		handlingAir: 0,
		handlingGty: 0.25,
		grip: 0.5,
		miniturbo: 0.25
	} as Stats,
	{
		name: 'Teddy Buggy',
		speedGnd: -0.25,
		speedWtr: -0.25,
		speedAir: 0.25,
		speedGty: 0,
		acceleration: 0.25,
		weight: 0,
		handlingGnd: 0.25,
		handlingWtr: 0,
		handlingAir: 0.25,
		handlingGty: 0,
		grip: 0,
		miniturbo: 0.25
	} as Stats,
	{
		name: 'Bone Rattler',
		speedGnd: 0.25,
		speedWtr: 0.5,
		speedAir: -0.75,
		speedGty: -0.25,
		acceleration: -0.75,
		weight: 0.5,
		handlingGnd: -0.5,
		handlingWtr: 0.75,
		handlingAir: -0.5,
		handlingGty: -0.5,
		grip: 0,
		miniturbo: -0.5
	} as Stats,
    {
		name: 'Splat Buggy',
		speedGnd: 0.25,
		speedWtr: -0.25,
		speedAir: 0,
		speedGty: 0.25,
		acceleration: -0.25,
		weight: -0.5,
		handlingGnd: -0.25,
		handlingWtr: 0.25,
		handlingAir: -0.5,
		handlingGty: 0.5,
		grip: 0,
		miniturbo: -0.25
	} as Stats,
	{
		name: 'Inkstriker',
		speedGnd: 0,
		speedWtr: 0,
		speedAir: 0.25,
		speedGty: 0.5,
		acceleration: -0.25,
		weight: 0.25,
		handlingGnd: -0.25,
		handlingWtr: 0,
		handlingAir: -0.25,
		handlingGty: 0.25,
		grip: 0.25,
		miniturbo: 0
	} as Stats
];

data.forEach(item => item.imageUrl = getImageUrl(item, PartType.Body));

export default data;