import PartType from '@entities/part-type-enum';
import Stats from '@entities/stats';
import getImageUrl from '@utils/getImageUrl';

const data: Stats[] = [
    {
        name: 'Standard',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Monster',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Roller',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: 0,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0.25,
        grip: -0.25,
        miniturbo: 0.75
    } as Stats,
    {
        name: 'Slim',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Slick',
        speedGnd: 0.5,
        speedWtr: -0.75,
        speedAir: -0.75,
        speedGty: 0.5,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.75,
        handlingAir: -0.5,
        handlingGty: -0.25,
        grip: -1.25,
        miniturbo: -0.75
    } as Stats,
    {
        name: 'Metal',
        speedGnd: 0.5,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: -0.25,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.25,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: -0.75,
        miniturbo: -0.75
    } as Stats,
    {
        name: 'Button',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: -0.5,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: -0.5,
        miniturbo: 0.5
    } as Stats,
    {
        name: 'Off-Road',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    } as Stats,
    {
        name: 'Sponge',
        speedGnd: -0.25,
        speedWtr: -0.5,
        speedAir: 0.25,
        speedGty: -0.25,
        acceleration: 0,
        weight: -0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.5,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Wood',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Cushion',
        speedGnd: -0.25,
        speedWtr: -0.5,
        speedAir: 0.25,
        speedGty: -0.25,
        acceleration: 0,
        weight: -0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.5,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: 0.25
    } as Stats,
    {
        name: 'Blue Standard',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Hot Monster',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Azure Roller',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: 0,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0.25,
        grip: -0.25,
        miniturbo: 0.75
    } as Stats,
    {
        name: 'Crimson Slim',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Cyber Slick',
        speedGnd: 0.5,
        speedWtr: -0.75,
        speedAir: -0.75,
        speedGty: 0.5,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.75,
        handlingAir: -0.5,
        handlingGty: -0.25,
        grip: -1.25,
        miniturbo: -0.75
    } as Stats,
    {
        name: 'Retro Off-Road',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    } as Stats,
    {
        name: 'Gold Tires',
        speedGnd: 0.5,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: -0.25,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.25,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: -0.75,
        miniturbo: -0.75
    } as Stats,
    {
        name: 'GLA Tires',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    } as Stats,
    {
        name: 'Triforce Tires',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    } as Stats,
    {
        name: 'Ancient Tires',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    } as Stats,
    {
        name: 'Leaf Tires',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: -0.5,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: -0.5,
        miniturbo: 0.5
    } as Stats
];

data.forEach(item => item.imageUrl = getImageUrl(item, PartType.Tire));

export default data;